from linked_list_simple import *
ll = linked_list()
ll.append(1)
ll.append(2)
ll.append(3)
ll.append(4)
ll.display()
ll.reverse()
ll.display()
#ll.sum_linked()
ll.append(5)
ll.sum_linked()
ll.max_val()